# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_date', models.DateField(auto_now=True)),
                ('notes', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Grain',
            fields=[
                ('baseingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.BaseIngredient')),
                ('supplier', models.CharField(max_length=200)),
                ('grain_type', models.IntegerField()),
                ('color', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grain_yield', models.DecimalField(decimal_places=2, max_digits=6)),
                ('coarse_fine_diff', models.DecimalField(decimal_places=2, max_digits=6)),
                ('moisture', models.DecimalField(decimal_places=2, max_digits=6)),
                ('diastatic_power', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ibu_gal_per_lb', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            bases=('ingredients.baseingredient',),
        ),
        migrations.CreateModel(
            name='Hop',
            fields=[
                ('baseingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.BaseIngredient')),
                ('alpha', models.DecimalField(decimal_places=2, max_digits=6)),
                ('beta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hsi', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            bases=('ingredients.baseingredient',),
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('baseingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.BaseIngredient')),
                ('pH', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calcium', models.DecimalField(decimal_places=2, max_digits=6)),
                ('magnesium', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sodium', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sulfate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('chloride', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bicarbonate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gypsum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('salt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('epsom', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cacl', models.DecimalField(decimal_places=2, max_digits=6)),
                ('soda', models.DecimalField(decimal_places=2, max_digits=6)),
                ('chalk', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            bases=('ingredients.baseingredient',),
        ),
        migrations.CreateModel(
            name='Yeast',
            fields=[
                ('baseingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ingredients.BaseIngredient')),
                ('product_id', models.CharField(max_length=20)),
                ('attenuation_low', models.DecimalField(decimal_places=2, max_digits=6)),
                ('attenuation_high', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flocculation', models.IntegerField()),
                ('temperature_low', models.DecimalField(decimal_places=2, max_digits=6)),
                ('temperature_high', models.DecimalField(decimal_places=2, max_digits=6)),
                ('best_for', models.CharField(max_length=200)),
            ],
            bases=('ingredients.baseingredient',),
        ),
    ]
